# Generated by Django 5.0.4 on 2024-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_alter_gamer_options_gamer_total_minutos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'ordering': ['dificult', 'total_minutos']},
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='time',
        ),
        migrations.AddField(
            model_name='gamer',
            name='final_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='gamer',
            name='initial_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
