# Generated by Django 5.0.4 on 2024-05-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_alter_gamer_options_remove_gamer_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'ordering': ['dificult', 'total_segundos']},
        ),
        migrations.RenameField(
            model_name='gamer',
            old_name='total_minutos',
            new_name='total_segundos',
        ),
    ]
