# Generated by Django 5.0.4 on 2024-05-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_gamer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='final_time',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='initial_time',
        ),
    ]
