# Generated by Django 5.0.4 on 2024-05-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_rename_servidordejuego_servidor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servidor',
            new_name='esparcimiento',
        ),
    ]
