# Generated by Django 5.0.4 on 2024-05-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_rename_servidor_esparcimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esparcimiento',
            name='dificultad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick5',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
