# Generated by Django 5.0.4 on 2024-05-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_alter_esparcimiento_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esparcimiento',
            name='dificultad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esparcimiento',
            name='nick5',
            field=models.CharField(default='', max_length=20),
        ),
    ]
