# Generated by Django 5.0.4 on 2024-05-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0013_esparcimiento_estado_de_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio',
            new_name='estado_de_inicio1',
        ),
        migrations.AddField(
            model_name='esparcimiento',
            name='estado_de_inicio2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='esparcimiento',
            name='estado_de_inicio3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='esparcimiento',
            name='estado_de_inicio4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='esparcimiento',
            name='estado_de_inicio5',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
