# Generated by Django 5.0.4 on 2024-05-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0014_rename_estado_de_inicio_esparcimiento_estado_de_inicio1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio1',
            new_name='nickstate1',
        ),
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio2',
            new_name='nickstate2',
        ),
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio3',
            new_name='nickstate3',
        ),
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio4',
            new_name='nickstate4',
        ),
        migrations.RenameField(
            model_name='esparcimiento',
            old_name='estado_de_inicio5',
            new_name='nickstate5',
        ),
    ]
