# Generated by Django 5.0.4 on 2024-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_rename_estado_de_inicio1_esparcimiento_nickstate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esparcimiento',
            name='inicio',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='esparcimiento',
            name='play',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
